var annotated_dup =
[
    [ "INTELLI", null, [
      [ "AbstractC20Thread", "classINTELLI_1_1AbstractC20Thread.html", "classINTELLI_1_1AbstractC20Thread" ],
      [ "C20Buffer", "classINTELLI_1_1C20Buffer.html", "classINTELLI_1_1C20Buffer" ],
      [ "ConfigMap", "classINTELLI_1_1ConfigMap.html", "classINTELLI_1_1ConfigMap" ],
      [ "IntelliLog", "classINTELLI_1_1IntelliLog.html", null ],
      [ "IntelliLog_FileProtector", "classINTELLI_1_1IntelliLog__FileProtector.html", "classINTELLI_1_1IntelliLog__FileProtector" ],
      [ "MicroDataSet", "classINTELLI_1_1MicroDataSet.html", "classINTELLI_1_1MicroDataSet" ],
      [ "SPSCQueue", "classINTELLI_1_1SPSCQueue.html", "classINTELLI_1_1SPSCQueue" ],
      [ "ThreadPerf", "classINTELLI_1_1ThreadPerf.html", "classINTELLI_1_1ThreadPerf" ],
      [ "UtilityFunctions", "classINTELLI_1_1UtilityFunctions.html", "classINTELLI_1_1UtilityFunctions" ]
    ] ],
    [ "OoOJoin", "namespaceOoOJoin.html", [
      [ "AbstractStateOfKey", "classOoOJoin_1_1AbstractStateOfKey.html", "classOoOJoin_1_1AbstractStateOfKey" ],
      [ "StateOfKeyBucket", "classOoOJoin_1_1StateOfKeyBucket.html", "classOoOJoin_1_1StateOfKeyBucket" ],
      [ "StateOfKeyHashTable", "classOoOJoin_1_1StateOfKeyHashTable.html", "classOoOJoin_1_1StateOfKeyHashTable" ],
      [ "Tuple", "classOoOJoin_1_1Tuple.html", "classOoOJoin_1_1Tuple" ],
      [ "OoOTuple", "classOoOJoin_1_1OoOTuple.html", "classOoOJoin_1_1OoOTuple" ],
      [ "TrackTuple", "classOoOJoin_1_1TrackTuple.html", "classOoOJoin_1_1TrackTuple" ],
      [ "Window", "classOoOJoin_1_1Window.html", "classOoOJoin_1_1Window" ],
      [ "AbstractJoinAlgo", "classOoOJoin_1_1AbstractJoinAlgo.html", "classOoOJoin_1_1AbstractJoinAlgo" ],
      [ "JoinAlgoTable", "classOoOJoin_1_1JoinAlgoTable.html", "classOoOJoin_1_1JoinAlgoTable" ],
      [ "NestedLoopJoin", "classOoOJoin_1_1NestedLoopJoin.html", "classOoOJoin_1_1NestedLoopJoin" ],
      [ "MtBucket", "classOoOJoin_1_1MtBucket.html", "classOoOJoin_1_1MtBucket" ],
      [ "MultiThreadHashTable", "classOoOJoin_1_1MultiThreadHashTable.html", "classOoOJoin_1_1MultiThreadHashTable" ],
      [ "NPJ_thread", "classOoOJoin_1_1NPJ__thread.html", "classOoOJoin_1_1NPJ__thread" ],
      [ "NPJ", "classOoOJoin_1_1NPJ.html", "classOoOJoin_1_1NPJ" ],
      [ "NPJSingle", "classOoOJoin_1_1NPJSingle.html", "classOoOJoin_1_1NPJSingle" ],
      [ "AbstractOperator", "classOoOJoin_1_1AbstractOperator.html", "classOoOJoin_1_1AbstractOperator" ],
      [ "IAWJOperator", "classOoOJoin_1_1IAWJOperator.html", "classOoOJoin_1_1IAWJOperator" ],
      [ "IMAIAWJOperator", "classOoOJoin_1_1IMAIAWJOperator.html", "classOoOJoin_1_1IMAIAWJOperator" ],
      [ "MeanAQPIAWJOperator", "classOoOJoin_1_1MeanAQPIAWJOperator.html", "classOoOJoin_1_1MeanAQPIAWJOperator" ],
      [ "OperatorTable", "classOoOJoin_1_1OperatorTable.html", "classOoOJoin_1_1OperatorTable" ],
      [ "AbstractDataLoader", "classOoOJoin_1_1AbstractDataLoader.html", "classOoOJoin_1_1AbstractDataLoader" ],
      [ "DataLoaderTable", "classOoOJoin_1_1DataLoaderTable.html", "classOoOJoin_1_1DataLoaderTable" ],
      [ "FileDataLoader", "classOoOJoin_1_1FileDataLoader.html", "classOoOJoin_1_1FileDataLoader" ],
      [ "RandomDataLoader", "classOoOJoin_1_1RandomDataLoader.html", "classOoOJoin_1_1RandomDataLoader" ],
      [ "TestBench", "classOoOJoin_1_1TestBench.html", "classOoOJoin_1_1TestBench" ],
      [ "ZipfDataLoader", "classOoOJoin_1_1ZipfDataLoader.html", "classOoOJoin_1_1ZipfDataLoader" ],
      [ "AbstractWaterMarker", "classOoOJoin_1_1AbstractWaterMarker.html", "classOoOJoin_1_1AbstractWaterMarker" ],
      [ "ArrivalWM", "classOoOJoin_1_1ArrivalWM.html", "classOoOJoin_1_1ArrivalWM" ],
      [ "LatenessWM", "classOoOJoin_1_1LatenessWM.html", "classOoOJoin_1_1LatenessWM" ],
      [ "WMTable", "classOoOJoin_1_1WMTable.html", "classOoOJoin_1_1WMTable" ]
    ] ],
    [ "default_attrs", "structdefault__attrs.html", null ]
];