#!/bin/bash
genRatio() {
ratioString=$1,$1,$1,$1,$1,
echo $ratioString > ratioDD_$1
}
testRatio(){
    rm -rf sec5_3_model/ratio_$1
    mkdir sec5_3_model/ratio_$1
    rm ratioDD_$1
    genRatio $1
    rm *.csv
    ./benchmark rovio 0 ratioDD_$1
    ./benchmark rovio 1 ratioDD_$1
    cp *.csv sec5_3_model/ratio_$1
}
rm -rf sec5_3_model
mkdir sec5_3_model
testRatio 0.1
#testRatio 0.2
#testRatio 0.3
#testRatio 0.4
#testRatio 0.5
#testRatio 0.6
#testRatio 0.7
#testRatio 0.8
testRatio 0.9
#emfun 50


    

